### ISSUE TITLE
Volume Convolution - Segmentation Fault on Large Sizes

### ISSUE THREAD

**Issue by av1659** [lupoglaz/TorchProteinLibrary#33]
Hello - For Volume Convolution, in the unit tests, if I change the box_size to 80, batch_size to 2, and number of channels to 48 -- for a volume of (2,48,80,80,80), then I get a segfault in cpu_VolumeConv when I run the Unit Tests. This size is required for some other code (https://github.com/lupoglaz/DeepLocalProteinDocking). Any advice on how to fix this? Thanks!

**Comment by lupoglaz** [comment]
Moved on with pytorch based fft functions
