### ISSUE TITLE
RMSD error about function not implemented

### ISSUE THREAD

**Issue by yuanqidu** [lupoglaz/TorchProteinLibrary#36]
FullAtomModel/CoordsTransform/CoordsTransform.py", line 174, in forward
    _FullAtomModel.Coords2CenterGPU_forward( input_coords, output_center, num_atoms)
RuntimeError: "Coords2CenterGPU_forward" not implemented for 'Half'

I am confused by why this happened. It looked like the function is not implemented?

**Comment by yuanqidu** [comment]
NVM, it was due to mixed-precision training.

**Comment by lupoglaz** [comment]
Yeah, right now there are no layers that are using half precision.
